### ISSUE TITLE
Regarding programming languages and runtime environments

### ISSUE THREAD

**Issue by AbdulazizGH** [techbench-sa/Participants-Guide#1]
Hey everyone,

First of all, thanks for all your hard working in managing these awesome events!👍

I was just lurking on your repo to find more details regarding the development aspects of the hackathon(so I can install the proper interpreters/compilers, etc), but I still have one more question:
Which version(s) of Python are supported in the hackathon? (3.x vs 2.x are widely incompatible)

Thanks again,
Abdulaziz

**Comment by mrokaini** [comment]
Hi Abdulaziz. 

We want to thank you for your excitement and initiative. 

Regarding your question, we will be using python 2.x or newer releases. 
More info about the system and the rules will be provided during the opening ceremony.

We are eager to see you there.
Mohannad.
